raise error if no package.json version; checkout workspace;

diff --git a/.github/workflows/linux-publish.yml b/.github/workflows/linux-publish.yml
--- a/.github/workflows/linux-publish.yml
+++ b/.github/workflows/linux-publish.yml
@@ -14,6 +14,9 @@ jobs:
     outputs:
       version: ${{ steps.parse.outputs.version }}
     steps:
+      - name: Checkout Workspace
+        uses: actions/checkout@v4
+
       - name: Derive version from tag or package
         id: parse
         shell: bash
@@ -27,6 +30,9 @@ jobs:
             if PACKAGE_VERSION=$(jq -r .version package.json)
             then
               echo "version=${PACKAGE_VERSION#v}-${GITHUB_RUN_ID}" | tee -a $GITHUB_OUTPUT
+            else
+              echo "ERROR: Could not find version in package.json"
+              exit 1
             fi
           else
             echo "version=${GITHUB_REF_NAME#app-ziti-console-v}" | tee -a $GITHUB_OUTPUT
@@ -39,7 +45,8 @@ jobs:
     env:
       BUILD_CONFIG: "Release"
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout Workspace
+        uses: actions/checkout@v4
 
       - uses: actions/setup-node@v4
         with:
